# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8cd88698d17051b0cbb66786f0b4375130693bb337ceaf8927cbd4b4e49c3e8348bd0f82350a4fa218e84c0bbf2d918c7e46b23d7fc0c260d10d7d5be76e953

test:
  secret_key_base: 70f3d181f3ce975d82e556e1f4154e08b0559ae5254437a0aa6525169626bc784a72402cc8ea142cfc1c77c763e0faaf94df5e93341fc3515600d3312b43e084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
